### ISSUE TITLE
Segmentation fault on Linux

### ISSUE THREAD

**Issue by przem360** [bosorioo/rts-game-console#2]
Hi!

I've compiled the game witout any issues, however every time I run it, it crashes immediately after selecting `Start New Game`.  
Maybe GDB log will help:  
```
...
+------------------------------------------------------------------------------+
|Selected unit: Headquarter                                                    |
|Health: 500/500  Income: 0.4/0.2                                              |
+Press 1 to hire a worker. Costs 10/4.-----------------------------------------+
Program received signal SIGSEGV, Segmentation fault.
0x000055555555ad09 in Unit_GetOwner ()
(gdb) backtrace
#0  0x000055555555ad09 in Unit_GetOwner ()
#1  0x000055555555778e in Display_DrawMap ()
#2  0x000055555555c966 in GamePlay_onRender ()
#3  0x00005555555567a9 in main ()
(gdb) 
```

I'm running 64-bit Linux with gcc version 11.4.0

**Comment by bosorioo** [comment]
Seems like the program crashes if the terminal window size is not big enough.
I made a few changes to try to address that and also added an alternative to run this project inside Docker, see if it helps.

**Comment by przem360** [comment]
You fixed it!
I havent try Docker but now it works, I can play :)
